### ISSUE TITLE
Main.cpp segfaults if IceStorm is not in config file.

### ISSUE THREAD

**Issue by pbustos** [robocomp/robocomp#247] opened 2020-03-06 12:36 UTC
If this line is not in the config file and the component publishes or subscribes to something, main.cpp segfaults without further information.

// This property is used by the clients to connect to IceStorm.
TopicManager.Proxy=IceStorm/TopicManager:default -p 9999

Also, when regenerating a component and including a subscribe entry in its cdsl, the TopicManager line is not included in the new config file.

**Comment by orensbruli** [comment] 2020-03-18 16:18
Hello Pablo,
Next time, it's easier to have different issues open for different problems.

For your last comment:
> Also, when regenerating a component and including a subscribe entry in its cdsl, the TopicManager line is not included in the new config file.

I can't reproduce it. 
I get this changes on the config file:
![image](https://user-images.githubusercontent.com/5784096/76979753-ad9c2d00-6938-11ea-819e-8591708b8261.png)

When I add the subscribesTo to the cdsl:
![image](https://user-images.githubusercontent.com/5784096/76982446-35376b00-693c-11ea-93de-94fd5c592fad.png)

**Comment by orensbruli** [comment] 2020-03-18 21:09
About the first issue you describe:
> If this line is not in the config file and the component publishes or subscribes to something, main.cpp segfaults without further information.
> 
> // This property is used by the clients to connect to IceStorm.
> TopicManager.Proxy=IceStorm/TopicManager:default -p 9999

I think it's been fixed with the commit https://github.com/robocomp/robocomp/commit/7c31593501339de1116cfb774344c9fa1c11e226
so I proceed to close this issue. If you can reproduce the second problem, please open a new issue.

It would be great if you can also check it.
Best.

**Closed** 2020-03-18 21:09 UTC
Labels: bug
